// this file is autogenerated - any modification will be overwritten
// unused symbols will not be linked in the final binary
// generated on 2022-11-11 19:19:16
// by ['.\\cert.py', '-s', 'api.telegram.org', '-n', 'telegram']

#pragma once

////////////////////////////////////////////////////////////
// certificate chain for api.telegram.org:443

const char* telegram_host = "api.telegram.org";
const uint16_t telegram_port = 443;

// CN: api.telegram.org => name: api_telegram_org
// not valid before: 2022-03-24 15:21:45
// not valid after:  2023-04-25 15:21:45
const char fingerprint_api_telegram_org [] PROGMEM = "07:36:89:3d:0f:cc:8c:f7:d0:19:b7:83:39:c4:d5:15:70:9a:c6:5d";
const char pubkey_api_telegram_org [] PROGMEM = R"PUBKEY(
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKMWnlxXyYll7ep4C66K
WC+uWshuSY38V6WYiHguCzxAPCEumpSYM6fjQqeF+tBzhAEccjk3I7VWHUOlcRQI
JKU5zN5YU5SOKkKnTi0HMp66i9MqqZ7A486aEJZFWHrHHkUUI5K7VIKIlEm2voEh
ACltyc6LOTrcNRXZ60ec77oJDhbk2etyMPpJq5gxfLOsKymRhwhBcl41x4cEIvVI
djBtiN/ypSkTcLOHAtVrWLHoc8fk73mGpAdfZ7R5jaQlAYKM4DAXy0tc++tMElG5
yQQfftL4uvU1jYocN4LwFXMAbj0cdosBdIE95CynzC9m3ESoJz/q0Keo8cvq2gc4
vQIDAQAB
-----END PUBLIC KEY-----
)PUBKEY";

// http://certificates.godaddy.com/repository/gdig2.crt
// CN: Go Daddy Secure Certificate Authority - G2 => name: Go_Daddy_Secure_Certificate_Authority___G2
// not valid before: 2011-05-03 07:00:00
// not valid after:  2031-05-03 07:00:00
const char cert_Go_Daddy_Secure_Certificate_Authority___G2 [] PROGMEM = R"CERT(
-----BEGIN CERTIFICATE-----
MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3
MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UE
CxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQD
EypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzD
BNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOv
K/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23e
cSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HY
pDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7n
eTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMB
AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV
HQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv
9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
b2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5n
b2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEG
CCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
MA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz
91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2
RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawi
DsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11
GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2x
LXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB
-----END CERTIFICATE-----
)CERT";

// end of certificate chain for api.telegram.org:443
////////////////////////////////////////////////////////////